version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi_app
    ports:
      - "8080:8080"
    volumes:
      - ./store_app:/app/store_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:1111@db/store_app

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: store_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
